In [3]:
import sys
sys.getsizeof(5)

28

In [4]:
ls = [1,2,3,4]
sys.getsizeof(ls)

88

In [5]:
ls2 = [2,3,4,5,6]
sys.getsizeof(ls2)

104

In [8]:
import numpy as np

In [11]:
sys.getsizeof(np.array([1,2,3]))

124

In [13]:
arr = np.array([1,2,3,4,5,6])

In [14]:
type(ls),type(arr)

(list, numpy.ndarray)

In [15]:
arr[0]

1

In [16]:
arr[2]

3

In [17]:
for i in arr:
    print(i)

1
2
3
4
5
6


In [19]:
5+5

10

# This is heading 1
## This is heading 2
### This is heading 3
This is heading </br> 
$\frac{1}{2}$

In [20]:
arr = np.array([1,2,3,4,5])

In [21]:
arr.dtype

dtype('int32')

In [22]:
arr2 = np.array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
arr2.dtype

dtype('float64')

In [24]:
sys.getsizeof(arr)

132

In [27]:
arr = np.array(arr,dtype=np.int8)

In [28]:
sys.getsizeof(arr)

117

In [29]:
arr3 = np.array(arr,dtype=np.float16)

In [30]:
strarr =  np.array(['a', 'b', 'c'])

In [31]:
type(strarr)

numpy.ndarray

# Dimension and Shapes

In [32]:
Al = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [33]:
for i in Al:
    for j in i:
        print(j,end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [34]:
for i in Al:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [35]:
A = np.array(Al,dtype=np.int8)

### Which one is method and which one is function?

In [36]:
A.shape

(3, 3)

In [38]:
A.ndim

2

In [39]:
B = np.array([[[1,2,3],[1,2,1],[1,2,3]]])

In [40]:
B.ndim

3

In [41]:
A.size

9

## Square Matrix

In [42]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [43]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
mat[0]

array([1, 2, 3])

In [45]:
mat[1]

array([4, 5, 6])

In [46]:
mat[2]

array([7, 8, 9])

In [47]:
mat[0][0]

1

In [48]:
mat[2][2]

9

In [50]:
size = mat.shape

In [51]:
size[0]

3

In [52]:
size[1]

3

In [53]:
type(size)

tuple

In [54]:
size

(3, 3)

In [55]:
for i in range(0,size[0]):
    for j in range(0,size[1]):
        print(mat[i][j])

1
2
3
4
5
6
7
8
9


In [56]:
x = np.arange(10)

In [57]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x[:4]

array([0, 1, 2, 3])

In [59]:
x[::2]

array([0, 2, 4, 6, 8])

In [60]:
x[-1]

9

In [61]:
x[:6:3]

array([0, 3])

In [62]:
xr = x[::-1]

In [63]:
xr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [65]:
A[1,1]

5

In [66]:
A[1][1]

5

### Summary Statistics
Generat 10000 data from standard normal distribution

In [73]:
x = np.random.normal(0,1,10000)

In [69]:
x[:10]

array([ 1.95249535,  1.07272153, -0.39716348,  0.34395342,  1.22013236,
       -2.66464426, -0.02457105,  0.38789866, -0.8048928 ,  0.74867042])

In [71]:
x[:10].sum()

1.8346001514583652

In [74]:
x.sum()

-127.49079043407292

In [75]:
x.var()

0.9918625226484712

In [76]:
x.std()

0.9959229501565225

In [81]:
x.mean()

-0.012749079043407292

X = x.reshape(10,1000)

In [82]:
X = x.reshape(10,1000)

In [84]:
X.shape

(10, 1000)

In [85]:
sys.getsizeof(X)

128

In [86]:
X.mean()

-0.012749079043407292

In [87]:
X.mean(axis=0)

array([-6.18069579e-01,  5.18218218e-01,  3.16050736e-01, -2.02229598e-01,
        2.49108215e-01,  8.47927231e-01,  2.12687795e-01,  4.53176714e-01,
        1.61886700e-01, -4.74288409e-01,  3.13826993e-01,  3.42241427e-01,
        2.78431292e-02,  9.10990886e-02,  1.75371775e-02, -6.40550919e-02,
       -7.01840766e-02,  6.36645444e-01, -4.61584622e-01, -2.67613651e-02,
        3.95290667e-01, -1.68763606e-01, -1.32960270e-01,  5.26020900e-03,
        6.34639157e-01, -6.78919083e-01,  2.85268768e-01, -3.06924288e-01,
       -1.10977198e-01,  1.60351803e-01,  1.76597173e-01,  1.50685099e-01,
       -3.93547514e-01, -4.19272116e-01, -1.21984790e-01, -1.72432233e-01,
       -2.35219410e-01, -5.02690419e-02, -4.72788079e-01,  2.89218241e-01,
        3.75046556e-01,  3.25909740e-01,  7.88771969e-02,  2.08554147e-01,
        4.71889282e-01, -1.33198183e-01,  5.70285640e-01,  4.20726482e-01,
       -6.29984574e-01,  2.94541248e-01, -2.37213408e-01,  7.42448372e-02,
        1.06503127e-03, -

In [88]:
X.mean(axis=1)

array([ 0.02770348,  0.00522924, -0.03888671, -0.00108039, -0.0694757 ,
        0.00758447, -0.05157693, -0.00796185,  0.01317052, -0.01219692])

In [95]:
X[::][1].mean() # just first column

0.005229244495523595

In [97]:
X.var(axis=1)

array([1.01574458, 0.9993106 , 1.0193925 , 0.93595137, 0.98524126,
       1.04996547, 0.99365366, 0.96487732, 1.00822594, 0.93764955])

In [101]:
A.sum(axis=1) # col sum

array([ 6, 15, 24])

In [102]:
A.sum(axis=0)

array([12, 15, 18])

In [103]:
A.sum()

45

In [104]:
A.sum(axis=0)

array([12, 15, 18])